[package]
name = "sqrl-protocol"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22.0"
ed25519-dalek = "2.1.1"
url = "2.5.0"

[dev-dependencies]
rand = "0.8.5"
