name: Rust

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Publish crate
      run: cargo publish --verbose --dry-run
    - name: Publish crate
      run: cargo publish --verbose --token ${{ secrets.CARGO_TOKEN }}
